name: CI Unit Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependency
        run: npm ci

      - name: Cek lint
        run: npm run lint

      - name: Build project
        run: npm run build
